logger:
  level: DEBUG
  log_interval: 10

setting:
  env_id: SimpleMiniGrid-Empty-5x5-v0
#  env_id: SimpleMiniGrid-Reward-5x5-v0
  render_mode: rgb_array
#  render_mode: human
  eval_steps: 1_000
  use_sf_paper_reward: True   # 1 if goal reached
  max_episode_steps: 20
  tasks: 1
  time_steps_per_task: 1_000

q_learning:
  alpha: 0.001
  epsilon: 1.0
  epsilon_decay: 0.9
  epsilon_lower_bound: 0.1
  gamma: 0.95
  initial_q_value: 0.0001

sfq_learning:
  alpha: 0.01
  alpha_w: 0.01
  epsilon: 0.15
  epsilon_decay: 1.0
  epsilon_lower_bound: 0.1
  gamma: 0.95
  initial_q_value: 0.01
  initial_w_value: 0.01

feature_extractor:
  max_rbf_grid_size: 3
  rbf_sigma: 0.1
  include_goal: False
  include_direction: False