logger:
  level: DEBUG
  log_interval: 10

setting:
  env_id: MiniGrid-Empty-5x5-v0
#  env_id: MiniGrid-FourRooms-v0
  render_mode: rgb_array
  eval_steps: 1_000
  use_sf_paper_reward: True   # 1 if goal reached

q_learning:
  alpha: 0.0005
  epsilon: 0.15
  epsilon_decay: 0.999
  epsilon_lower_bound: 0.1
  gamma: 0.95
  initial_q_value: 0.0001
  tasks: 1
  time_steps_per_task: 20_000

feature_extractor:
  max_rbf_grid_size: 3
  rbf_sigma: 0.1
  include_goal: False